site_name: To Not Forget
site_author: storm-wind

nav:
  - Home: index.md
  - Linux:
    - Cron: linux/cron.md
    - Docker: linux/docker.md
    - Logrotate: linux/logrotate.md
    - LVM: linux/lvm.md
    - Podman: linux/podman.md
    - Proxmox: linux/proxmox.md
  - Windows:
    - WSL: windows/wsl.md
  - Platforms:
    - AWS:
      - AWS CLI: platforms/awscli.md
    - Cloudflare:
      - Argo: platforms/argo.md
    - VMware: platforms/vmware.md
  - Networks:
    - Proxies:
      - HAProxy: networks/haproxy.md
    - Security:
      - Openssl: security/openssl.md
      - Stunnel: networks/stunnel.md
      
#theme: windmill-dark
plugins:
  - search:
      min_search_length: 3
      prebuild_index: true
#theme: bootstrap
theme:
  name:  material
