site_name: To Not Forget
site_author: storm-wind

nav:
  - Home: index.md
  - Docker: tech/docker.md
  - LVM: tech/lvm.md
  - Podman: tech/podman.md
  - VMware: tech/vmware.md
  - WSL: tech/wsl.md
  
#theme: windmill-dark
plugins:
  - search:
      min_search_length: 3
      prebuild_index: true
#theme: bootstrap
theme:
  name:  material
