site_name: Synaptic Recall
site_author: storm-wind

nav:
  - Home: index.md
  - Databases:
    - MySQL: 
      - MySQL Ops: databases/mysql-ops.md
      - Replication: databases/mysql-rep.md
      - MYSQL General: databases/mysqlgen.md
    - Postgres:
      - Useful Commands: databases/postgres.md
  - Linux:
    - AD: linux/ad.md
    - Bash: linux/bash.md
    - Cron: linux/cron.md
    - Docker: linux/docker.md
    - FileSystems: linux/filesystems.md
    - Firewalld: linux/firewalld.md
    - Logrotate: linux/logrotate.md
    - LVM: linux/lvm.md
    - Mail: linux/mail.md
    - Nano: linux/nano.md
    - Networking: linux/networking.md
    - Podman: linux/podman.md
    - Pi: linux/raspberry-pi.md
    - RHEL: linux.md/redhat.md
    - Swap: linux/swap.md
    - Useful Commands: linux/useful.md
    - Zerotier: networks/zerotier.md
  - Monitoring:
    - Prometheus: monitoring/prometheus.md
  - Windows:
    - WSL: windows/wsl.md
    - RDP: windows/windows.md
    - Powershell: windows/adduserstogroup.md
  - Platforms:
    - AWS:
      - AWS CLI: platforms/awscli.md
      - AWS Gen: platforms/awsgen.md
    - Azure:
      - Azure CLI: platforms/azure.md
    - Cisco EPNMN:
      - EPNMN CLI: platforms/ciscoepnmn.md
    - Cloudflare:
      - Argo: platforms/argo.md
    - Proxmox: platforms/proxmox.md
    - VMware: platforms/vmware.md
  - Networks:
    - Proxies:
      - HAProxy: networks/haproxy.md
      - Nginx: networks/nginx.md
    - Security:
      - openssl: security/openssl.md
      - Stunnel: networks/stunnel.md
      - Nessus: security/nessus.md 

#theme: windmill-dark
plugins:
  - search:
      min_search_length: 3
      prebuild_index: true
#theme: bootstrap
theme:
  name:  material

docs:
   img:
      test.png


markdown_extensions:
  - attr_list
