site_name: To Not Forget
site_author: storm-wind

nav:
  - Home: index.md
  - About: about.md
  - Linux: tech/linux.md
#theme: windmill-dark
plugins:
  - search:
      min_search_length: 3
      prebuild_index: true
#theme: bootstrap
theme:
  name:  material
