site_name: To Not Forget
site_author: storm-wind

nav:
  - Home: index.md
  - Linux:
    - Docker: linux/docker.md
    - LVM: linux/lvm.md
    - Podman: linux/podman.md
    - Proxmox: linux/proxmox.md
  - Windows:
    - WSL: windows/wsl.md
  - Platforms:
    - AWS: platforms/awscli.md    
    - Cloudflare:
      - Argo: platforms/argo.md
    - VMware: platforms/vmware.md
  
#theme: windmill-dark
plugins:
  - search:
      min_search_length: 3
      prebuild_index: true
#theme: bootstrap
theme:
  name:  material
