site_name: My Documentation
nav:
  - Home: index.md
  - About: about.md
  - Linux: linux.md
theme: windmill-dark
#theme: bootstrap
#theme: bootstrap4
#theme:
#  name: gitbook
#theme:
#  name:  material
